apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-flask-app
  name: my-flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-flask-app
  strategy: {}
  template:
    metadata:
      labels:
        app: my-flask-app
    spec:
      containers:
      - image: us.gcr.io/black-beach-295409/my_flask_app:v.2.0.0
        imagePullPolicy: Always 
        name: myflaskapp
        ports:
        - containerPort: 8443
        resources: {}
        volumeMounts: 
        - name: tls 
          mountPath: /etc/tls 
          readOnly: true
        env: 
        - name: TLS_CERT
          value: /etc/tls/tls.crt
        - name: TLS_KEY
          value: /etc/tls/tls.key 
      volumes: 
        - name: tls 
          secret: 
           secretName: nitya-flask-tls 
