apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: my-flask-app
  name: my-flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-flask-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-flask-app
    spec:
      containers:
      - image: us.gcr.io/black-beach-295409/my_flask_app:v.1.0.0 
        name: myflaskapp
        resources: {}
