apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-flask-app
  name: my-flask-app
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: my-flask-app
