apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-flask-app
  name: my-flask-app-svc
  annotations: 
   cloud.google.com/app-protocols: '{"nitya-flask-tls":"HTTPS"}'
spec:
  type: NodePort
  ports:
  - name: nitya-flask-tls
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: my-flask-app
