apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: my-flask-app
  name: my-flask-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: my-flask-app
